### Get all rallies
GET http://localhost:8080/api/v1/rallies

### Get rally by ID
GET http://localhost:8080/api/v1/rallies/9

### Create a new rally
POST http://localhost:8080/api/v1/rallies
Content-Type: application/json

{
  "name": "Monte Carlo",
  "date": "2026-01-22"
}

### Update a Rally
PUT http://localhost:8080/api/v1/rallies/9
Content-Type: application/json

{
  "name": "Monte Tarlo",
  "date": "2026-05-20"
}